### ISSUE TITLE
能添加一个排序字段不，如图，按照升序或者降序排列

### ISSUE THREAD

**Issue by fhefh2015** [ZY2071/JueJin-Search#1]
![image](https://user-images.githubusercontent.com/14891797/80910444-13fed280-8d62-11ea-89b9-ade77c69c1c2.png)

**Comment by poozhu** [comment]
https://github.com/ZY2071/JueJin-Search/blob/c6d3f5819520936e4043e9b9b5a016b59ed304db/index.js#L20
我目前默认了按发布时间排序，需要其他方式的排序的话，新增一个排序的函数，然后直接使用新的排序函数即可，也可以通过传递参数来切换为另外的排序函数
